### ISSUE TITLE
StringIndexOutOfBoundsException when attaching to liberty profile

### ISSUE THREAD

**Issue by bmhm** [jvm-profiling-tools/honest-profiler#249]
When attaching to liberty profile, I get this error:

```
java.lang.StringIndexOutOfBoundsException: String index out of range: -609
	at java.lang.String.substring(String.java:1967)
	at com.insightfullogic.honest_profiler.core.sources.VirtualMachine.getLogSourceFromVmArgs(VirtualMachine.java:73)
	at com.insightfullogic.honest_profiler.ports.javafx.model.task.InitializeProfileTask.monitor(InitializeProfileTask.java:80)
	at com.insightfullogic.honest_profiler.ports.javafx.model.task.InitializeProfileTask.call(InitializeProfileTask.java:45)
	at com.insightfullogic.honest_profiler.ports.javafx.model.task.InitializeProfileTask.call(InitializeProfileTask.java:22)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Also, I cannot run this agent with IBM java. It just crashes and creates a core dump. But the wiki does not say "only oracle jvms supported".

**Comment by RichardWarburton** [comment]
IBM Java is not supported. See notes on JDK Version - https://github.com/jvm-profiling-tools/honest-profiler/wiki/How-to-build
