### ISSUE TITLE
also with openjdk: StringIndexOutOfBoundsException when attaching to liberty profile

### ISSUE THREAD

**Issue by bmhm** [jvm-profiling-tools/honest-profiler#250]
You closed #249 to soon.

go to https://adoptopenjdk.net/ and choose a openjdk-**j9** build.

You say on your wiki ANY OPENJDK will work for the agent.

Please fix, so it will also work on openjdk from eclipse (j9 engine).

```
java.lang.StringIndexOutOfBoundsException: String index out of range: -609
	at java.lang.String.substring(String.java:1967)
	at com.insightfullogic.honest_profiler.core.sources.VirtualMachine.getLogSourceFromVmArgs(VirtualMachine.java:73)
	at com.insightfullogic.honest_profiler.ports.javafx.model.task.InitializeProfileTask.monitor(InitializeProfileTask.java:80)
	at com.insightfullogic.honest_profiler.ports.javafx.model.task.InitializeProfileTask.call(InitializeProfileTask.java:45)
	at com.insightfullogic.honest_profiler.ports.javafx.model.task.InitializeProfileTask.call(InitializeProfileTask.java:22)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by RichardWarburton** [comment]
Fixed.
