### ISSUE TITLE
Unreported BufferUnderflowException

### ISSUE THREAD

**Issue by FauxFaux** [jvm-profiling-tools/honest-profiler#45]
While this (or possibly any?) log file is being written, both the console and javafx UIs print this to the console, but continue as if it hasn't happened.

 I can't share the log file.

```
java.nio.BufferUnderflowException
    at java.nio.Buffer.nextGetIndex(Buffer.java:506)
    at java.nio.DirectByteBuffer.getInt(DirectByteBuffer.java:677)
    at com.insightfullogic.honest_profiler.core.parser.LogParser.readStackFrame(LogParser.java:72)
    at com.insightfullogic.honest_profiler.core.parser.LogParser.readRecord(LogParser.java:42)
    at com.insightfullogic.honest_profiler.core.DataConsumer.accept(DataConsumer.java:31)
    at com.insightfullogic.honest_profiler.core.LogConsumer.run(LogConsumer.java:29)
    at com.insightfullogic.honest_profiler.core.Conductor.consumeFile(Conductor.java:31)
    at com.insightfullogic.honest_profiler.delivery.javafx.landing.LandingViewModel.open(LandingViewModel.java:61)
```

Both UIs seem also to not be processing the whole log, but aren't getting useful information out of it:  (The code isn't using ZipFile or nanoTime or Permissions or files or..., I suspect these entries are from the nanoseconds after the thing started, before the "error" in the log?):

```
Number of stack traces: 123397

Flat Profile:
 0.00 java.util.zip.ZipFile.open
 0.00 java.lang.System.nanoTime
 0.00 java.security.Permissions.add
 0.00 java.io.UnixFileSystem.getBooleanAttributes0
 0.00 java.util.zip.ZipFile.<init>
 0.00 java.util.jar.JarVerifier.<init>
```

**Comment by RichardWarburton** [comment]
I actually spotted and fixed another way this could have been happening last night. So if it still happens, might be worth downloading a new honest-profiler build.
